local linters = require("lvim.lsp.null-ls.linters")
linters.setup({
  -- { name = "alex" },
  { name = "buf" },
  { name = "buildifier" },
  { name = "checkstyle" },
  -- { name = "clj-kondo" },
  -- { name = "cmakelang" },
  -- { name = "cmakelint" },
  -- { name = "cmake-lint" },
  -- { name = "codespell" },
  { name = "commitlint" },
  -- { name = "cspell" },
  -- { name = "eslint_d" },
  -- { name = "flake8" },
  -- { name = "gdtoolkit" },
  -- { name = "gitleaks" },
  { name = "gitlint" },
  -- { name = "golangci-lint" },
  -- { name = "hadolint" },
  -- { name = "haml-lint" },
  -- { name = "joker" },
  { name = "jsonlint" },
  { name = "ktlint" },
  { name = "luacheck" },
  -- { name = "markdownlint" },
  -- { name = "misspell" },
  -- { name = "mypy" },
  -- { name = "oxlint" },
  -- { name = "phpcs" },
  -- { name = "phpstan" },
  { name = "proselint" },
  { name = "protolint" },
  -- { name = "pydocstyle" },
  -- { name = "pyflakes" },
  -- { name = "pylama" },
  -- { name = "pylint" },
  -- { name = "pyproject-flake8" },
  -- { name = "pyre" },
  -- { name = "revive" },
  { name = "rstcheck" },
  -- { name = "rubocop" },
  -- { name = "ruff" },
  -- { name = "selene" },
  -- { name = "semgrep" },
  {
    name = "shellcheck",
    filetypes = { "sh", "zsh", "bash" },
    args = { "--severity", "warning", "--shell", "bash" },
  },
  -- { name = "shellharden" },
  { name = "solhint" },
  -- { name = "sonarlint-language-server" }, -- TODO
  { name = "sqlfluff" },
  -- { name = "standardjs" },
  -- { name = "standardrb" },
  -- { name = "stylelint" },
  -- { name = "textlint" },
  -- { name = "tflint" },
  -- { name = "tfsec" },
  -- { name = "trufflehog" },
  -- { name = "ts-standard" },
  -- { name = "twigcs" },
  -- { name = "typos" },
  -- { name = "vacuum" },
  -- { name = "verible" },
  -- { name = "vint" },
  -- { name = "vulture" },
  -- { name = "woke" },
  -- { name = "write-good" },
  -- { name = "xo" },
  { name = "yamllint" },
  -- { name = "easy-coding-standard" },
  -- { name = "gospel" },
  -- { name = "staticcheck" },
  -- { name = "tlint" },
  -- { name = "trivy" },

  -- {
  --   name = "vale"
  --   args = { "configPath=~/.config/vale/vale.ini" },
  -- }""

})
